name = "milk"

can_rotate = true
can_reverse = false

pieces = '''
#####
   #

#####
    #

####
# #

####
   ##

###
# ##

###
 ###

###
##
#

###
# #
#

###
  ##
  #

 ##
##
 ##

 #
####
 #
'''

board = '''
###########
###########
###########
###########
###########
###########
'''

