can_rotate = true
can_reverse = true

pieces = '''
#####

####
#

####
 #

###
##

###
# #

###
  ##

###
#
#

###
 #
 #

##
 #
 ##

 #
###
 #

 ##
##
#

 ##
##
 #
'''

board = '''
 ######
########
########
########
########
########
########
 ######
'''

